name: test
description: Test application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
  data:  
    path: ./data
  navigation:
    path: ./navigation  
  home: 
    path: ./features/home  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/