name: core
description: Application core layer.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

   #firebase
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  #network
  dio: ^5.3.3
  #dependency injection
  get_it: ^7.6.0
  #base
  equatable: ^2.0.5
  #bloc
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  #locale storage
  shared_preferences: ^2.2.2
  #json annotation
  json_annotation: ^4.8.1
  #base
  logger: ^2.0.2+1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
flutter:

